apiVersion: batch/v1
kind: Job
metadata:
  name: allocate-rwx-jenkins-home-${DOMAIN}-0
spec:
  template:
    spec:
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: pvc-rwx-jenkins-home-${DOMAIN}-0
      containers:
        - name: busybox
          image: busybox
          command: ["true"]
          volumeMounts:
            - mountPath: /var/volume
              name: volume
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
      restartPolicy: Never
  backoffLimit: 4