apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-jenkins-home-$DOMAIN-0
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    #This would be the EBS volume ID , volume gets restored from EBS Snappshot
    volumeID: $VOLUMEID
  capacity:
    storage: 50Gi
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - us-east-1a
        - key: topology.kubernetes.io/region
          operator: In
          values:
          - us-east-1
  persistentVolumeReclaimPolicy: Delete
  storageClassName: gp2
  volumeMode: Filesystem
