apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-jenkins-home-${CONTROLLER_NAME}-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp2
  volumeMode: Filesystem
  volumeName: backup-jenkins-home-$CONTROLLER_NAME-0
