apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rwx-jenkins-home-${CONTROLLER_NAME}-0
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi # Change this to whatever your storage class requires, or to your needs
